-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.bill_books (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_by uuid NOT NULL,
  prefix character varying DEFAULT NULL::character varying,
  from_number integer NOT NULL,
  to_number integer NOT NULL,
  digits integer NOT NULL DEFAULT 4,
  postfix character varying DEFAULT NULL::character varying,
  branch_id uuid,
  consignor_id uuid,
  current_number integer NOT NULL,
  is_fixed boolean DEFAULT false,
  auto_continue boolean DEFAULT false,
  is_active boolean DEFAULT true,
  is_completed boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT bill_books_pkey PRIMARY KEY (id),
  CONSTRAINT bill_books_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.bill_company_profile (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_name character varying NOT NULL,
  gst_num character varying,
  pan character varying,
  adhar character varying,
  mobile_number character varying,
  alternate_number character varying,
  email character varying,
  company_address text,
  city character varying,
  state character varying,
  pincode character varying,
  stakeholder_type character varying NOT NULL CHECK (stakeholder_type::text = ANY (ARRAY['CONSIGNOR'::character varying, 'CONSIGNEE'::character varying, 'TRANSPORT'::character varying]::text[])),
  outstanding_amount numeric NOT NULL DEFAULT 0,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public.bill_details (
  detail_id integer NOT NULL DEFAULT nextval('bill_details_detail_id_seq'::regclass),
  bill_id integer NOT NULL,
  grno character varying NOT NULL,
  date date NOT NULL,
  consignor character varying,
  consignee character varying,
  city character varying,
  no_of_pckg integer,
  wt numeric,
  pvt_marks character varying,
  delivery_type character varying,
  pay_mode character varying,
  rate_by_kg numeric,
  labour_rate numeric,
  freight_amount numeric,
  labour_charge numeric,
  dd_charge numeric,
  toll_charge numeric,
  pf_charge numeric,
  other_charge numeric,
  bilty_total numeric,
  bill_charge numeric DEFAULT 0,
  CONSTRAINT bill_details_pkey PRIMARY KEY (detail_id),
  CONSTRAINT fk_bill FOREIGN KEY (bill_id) REFERENCES public.bill_master(bill_id)
);
CREATE TABLE public.bill_master (
  bill_id integer NOT NULL DEFAULT nextval('monthly_bills_bill_id_seq'::regclass),
  bill_number character varying,
  bill_date date,
  bill_month integer,
  bill_year integer,
  party_name character varying,
  billing_type character varying,
  status character varying DEFAULT 'Draft'::character varying,
  created_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT bill_master_pkey PRIMARY KEY (bill_id)
);
CREATE TABLE public.bilty (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  gr_no character varying NOT NULL,
  branch_id uuid NOT NULL,
  staff_id uuid NOT NULL,
  from_city_id uuid,
  to_city_id uuid,
  bilty_date date NOT NULL,
  delivery_type character varying,
  consignor_name character varying NOT NULL,
  consignor_gst character varying,
  consignor_number character varying,
  consignee_name character varying,
  consignee_gst character varying,
  consignee_number character varying,
  transport_name character varying,
  transport_gst character varying,
  transport_number character varying,
  payment_mode character varying,
  contain text,
  invoice_no character varying,
  invoice_value numeric DEFAULT 0,
  invoice_date date,
  e_way_bill character varying,
  document_number character varying,
  no_of_pkg integer DEFAULT 0,
  wt numeric,
  rate numeric,
  pvt_marks text,
  freight_amount numeric,
  labour_charge numeric,
  bill_charge numeric,
  toll_charge numeric,
  dd_charge numeric,
  other_charge numeric,
  total numeric,
  remark text,
  saving_option character varying DEFAULT 'SAVE'::character varying,
  is_active boolean DEFAULT true,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  pf_charge numeric DEFAULT 0,
  labour_rate numeric DEFAULT NULL::numeric,
  bilty_image text,
  transport_id uuid,
  pdf_bucket text,
  CONSTRAINT bilty_pkey PRIMARY KEY (id)
);
CREATE TABLE public.bilty_wise_kaat (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  gr_no character varying NOT NULL UNIQUE,
  challan_no character varying,
  destination_city_id uuid,
  transport_hub_rate_id uuid,
  rate_type character varying,
  rate_per_kg numeric DEFAULT 0,
  rate_per_pkg numeric DEFAULT 0,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  kaat numeric DEFAULT 0,
  pf numeric DEFAULT 0,
  actual_kaat_rate numeric DEFAULT 0,
  dd_chrg numeric DEFAULT 0,
  bilty_chrg numeric DEFAULT 0,
  ewb_chrg numeric DEFAULT 0,
  labour_chrg numeric DEFAULT 0,
  other_chrg numeric DEFAULT 0,
  pohonch_no character varying,
  bilty_number character varying,
  transport_id uuid,
  CONSTRAINT bilty_wise_kaat_pkey PRIMARY KEY (id),
  CONSTRAINT bilty_wise_kaat_transport_id_fkey FOREIGN KEY (transport_id) REFERENCES public.transports(id)
);
CREATE TABLE public.branch_finance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  branch_name character varying NOT NULL UNIQUE,
  location character varying,
  contact_number character varying,
  is_active boolean DEFAULT true,
  created_by_staff_id uuid NOT NULL,
  updated_by_staff_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT branch_finance_pkey PRIMARY KEY (id)
);
CREATE TABLE public.branches (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  branch_code character varying NOT NULL UNIQUE,
  city_code character varying NOT NULL,
  address text NOT NULL,
  manager_id uuid,
  branch_name character varying NOT NULL,
  default_bill_book_id uuid,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT branches_pkey PRIMARY KEY (id),
  CONSTRAINT branches_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES public.users(id)
);
CREATE TABLE public.challan_books (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_by uuid NOT NULL,
  prefix character varying DEFAULT NULL::character varying,
  from_number integer NOT NULL,
  to_number integer NOT NULL,
  digits integer NOT NULL DEFAULT 4,
  postfix character varying DEFAULT NULL::character varying,
  from_branch_id uuid NOT NULL,
  to_branch_id uuid NOT NULL,
  branch_1 uuid NOT NULL,
  branch_2 uuid,
  branch_3 uuid,
  current_number integer NOT NULL,
  is_fixed boolean DEFAULT false,
  auto_continue boolean DEFAULT false,
  is_active boolean DEFAULT true,
  is_completed boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT challan_books_pkey PRIMARY KEY (id),
  CONSTRAINT challan_books_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT challan_books_from_branch_id_fkey FOREIGN KEY (from_branch_id) REFERENCES public.branches(id),
  CONSTRAINT challan_books_to_branch_id_fkey FOREIGN KEY (to_branch_id) REFERENCES public.branches(id),
  CONSTRAINT challan_books_branch_1_fkey FOREIGN KEY (branch_1) REFERENCES public.branches(id),
  CONSTRAINT challan_books_branch_2_fkey FOREIGN KEY (branch_2) REFERENCES public.branches(id),
  CONSTRAINT challan_books_branch_3_fkey FOREIGN KEY (branch_3) REFERENCES public.branches(id)
);
CREATE TABLE public.challan_details (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  challan_no character varying NOT NULL UNIQUE,
  branch_id uuid NOT NULL,
  truck_id uuid,
  owner_id uuid,
  driver_id uuid,
  date date NOT NULL DEFAULT CURRENT_DATE,
  total_bilty_count integer DEFAULT 0,
  remarks text,
  is_active boolean DEFAULT true,
  is_dispatched boolean DEFAULT false,
  dispatch_date timestamp with time zone,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  is_received_at_hub boolean DEFAULT false,
  received_at_hub_timing timestamp with time zone,
  received_by_user uuid,
  CONSTRAINT challan_details_pkey PRIMARY KEY (id),
  CONSTRAINT challan_details_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT challan_details_truck_id_fkey FOREIGN KEY (truck_id) REFERENCES public.trucks(id),
  CONSTRAINT challan_details_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.staff(id),
  CONSTRAINT challan_details_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.staff(id),
  CONSTRAINT challan_details_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.challan_expenses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  challan_id uuid,
  challan_no text,
  loading_labour numeric DEFAULT 0,
  unloading_labour numeric DEFAULT 0,
  driver_expense numeric DEFAULT 0,
  cell_tax numeric DEFAULT 0,
  grease numeric DEFAULT 0,
  uncle_g numeric DEFAULT 0,
  cc_other numeric DEFAULT 0,
  diesel numeric DEFAULT 0,
  crossing numeric DEFAULT 0,
  total_kaat numeric DEFAULT 0,
  total_pf numeric DEFAULT 0,
  total_profit numeric DEFAULT 0,
  remarks text,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT challan_expenses_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cities (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  city_code character varying NOT NULL UNIQUE,
  city_name character varying NOT NULL,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cities_pkey PRIMARY KEY (id)
);
CREATE TABLE public.complaints (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  complaint_no character varying NOT NULL UNIQUE,
  gr_no character varying NOT NULL,
  bilty_id uuid NOT NULL,
  complaint_type character varying NOT NULL,
  complaint_description text,
  priority character varying DEFAULT 'MEDIUM'::character varying,
  status character varying NOT NULL DEFAULT 'INVESTIGATING'::character varying,
  destination_city character varying,
  challan_no character varying,
  is_out_for_delivery boolean DEFAULT false,
  is_at_hub boolean DEFAULT false,
  is_out_for_delivery_from_hub boolean DEFAULT false,
  expected_delivery_date date,
  actual_delivery_date timestamp with time zone,
  resolution_notes text,
  is_delivered_at_destination boolean DEFAULT false,
  resolved_at timestamp with time zone,
  resolved_by uuid,
  created_by uuid NOT NULL,
  updated_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  closed_at timestamp with time zone
);
CREATE TABLE public.consignees (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_name character varying NOT NULL,
  company_add text NOT NULL,
  number character varying,
  gst_num character varying,
  adhar character varying,
  pan character varying,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT consignees_pkey PRIMARY KEY (id)
);
CREATE TABLE public.consignor_bilty_profile (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  consignor_id uuid NOT NULL,
  destination_station_id uuid NOT NULL,
  city_code text,
  city_name text,
  transport_name text,
  transport_gst text,
  rate numeric NOT NULL DEFAULT 0,
  rate_unit text NOT NULL CHECK (rate_unit = ANY (ARRAY['PER_KG'::text, 'PER_NAG'::text])),
  minimum_weight_kg numeric DEFAULT 0,
  labour_rate numeric NOT NULL DEFAULT 0,
  labour_unit text CHECK (labour_unit = ANY (ARRAY['PER_KG'::text, 'PER_NAG'::text, 'PER_BILTY'::text])),
  dd_charge_per_kg numeric DEFAULT 0,
  dd_charge_per_nag numeric DEFAULT 0,
  receiving_slip_charge numeric DEFAULT 0,
  bilty_charge numeric DEFAULT 0,
  is_no_charge boolean DEFAULT false,
  effective_from date NOT NULL DEFAULT CURRENT_DATE,
  effective_to date,
  is_active boolean DEFAULT true,
  created_by uuid,
  updated_by uuid,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  dd_print_charge_per_kg numeric,
  dd_print_charge_per_nag numeric,
  is_toll_tax_applicable boolean DEFAULT false,
  toll_tax_amount numeric DEFAULT 0,
  freight_minimum_amount numeric DEFAULT 0,
  CONSTRAINT consignor_bilty_profile_pkey PRIMARY KEY (id)
);
CREATE TABLE public.consignor_otp_records (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  consignor_id uuid,
  phone_number character varying,
  otp_code character varying,
  purpose character varying DEFAULT 'login'::character varying,
  is_verified boolean DEFAULT false,
  is_expired boolean DEFAULT false,
  attempt_count integer DEFAULT 0,
  expires_at timestamp with time zone,
  verified_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT consignor_otp_records_pkey PRIMARY KEY (id)
);
CREATE TABLE public.consignor_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  consignor_id uuid,
  session_token text,
  is_revoked boolean DEFAULT false,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  last_used_at timestamp with time zone,
  device_info text,
  CONSTRAINT consignor_sessions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.consignors (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_name character varying NOT NULL,
  company_add text NOT NULL,
  number character varying,
  gst_num character varying,
  adhar character varying,
  pan character varying,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT consignors_pkey PRIMARY KEY (id)
);
CREATE TABLE public.consolidated_ewb_validations (
  id bigint NOT NULL DEFAULT nextval('consolidated_ewb_validations_id_seq'::regclass),
  validated_by uuid NOT NULL,
  challan_no character varying,
  consolidated_ewb_number character varying NOT NULL,
  total_ewb_count integer DEFAULT 0,
  is_valid boolean NOT NULL DEFAULT false,
  validation_status character varying,
  error_message text,
  included_ewb_numbers ARRAY,
  raw_result_metadata jsonb,
  validated_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT consolidated_ewb_validations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.content_management (
  content_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  content_name character varying NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT content_management_pkey PRIMARY KEY (content_id)
);
CREATE TABLE public.daily_branch_summary (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  branch_id uuid NOT NULL,
  summary_date date NOT NULL DEFAULT CURRENT_DATE,
  opening_balance numeric NOT NULL DEFAULT 0.00,
  total_income numeric DEFAULT 0.00,
  total_expense numeric DEFAULT 0.00,
  closing_balance numeric DEFAULT ((opening_balance + total_income) - total_expense),
  created_by_staff_id uuid NOT NULL,
  updated_by_staff_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT daily_branch_summary_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ewb_validations (
  id bigint NOT NULL DEFAULT nextval('ewb_validations_id_seq'::regclass),
  validated_by uuid NOT NULL,
  challan_no character varying,
  gr_no character varying,
  ewb_number character varying NOT NULL,
  is_valid boolean NOT NULL DEFAULT false,
  validation_status character varying,
  error_message text,
  raw_result_metadata jsonb,
  validated_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  valid_upto timestamp with time zone,
  created_by uuid,
  updated_by uuid,
  CONSTRAINT ewb_validations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.expense_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  branch_id uuid NOT NULL,
  transaction_date date NOT NULL DEFAULT CURRENT_DATE,
  party_name character varying NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  payment_mode character varying NOT NULL CHECK (payment_mode::text = ANY (ARRAY['cash'::character varying, 'online'::character varying]::text[])),
  sender character varying NOT NULL,
  description text,
  created_by_staff_id uuid NOT NULL,
  updated_by_staff_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT expense_transactions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.extended_ewb_validations (
  id bigint NOT NULL DEFAULT nextval('extended_ewb_validations_id_seq'::regclass),
  extended_by uuid NOT NULL,
  challan_no character varying,
  ewb_number character varying NOT NULL,
  is_success boolean NOT NULL DEFAULT false,
  vehicle_number character varying,
  mode_of_transport character varying,
  transport_mode_label character varying,
  place_of_consignor character varying,
  state_of_consignor character varying,
  remaining_distance integer,
  from_pincode character varying,
  consignment_status character varying,
  transit_type character varying,
  extend_validity_reason character varying,
  extend_remarks character varying,
  transporter_document_number character varying,
  transporter_document_date character varying,
  valid_upto character varying,
  updated_date character varying,
  pdf_url text,
  error_message text,
  raw_result_metadata jsonb,
  extended_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT extended_ewb_validations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.gr_reservations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  bill_book_id uuid NOT NULL,
  branch_id uuid NOT NULL,
  gr_no character varying NOT NULL,
  gr_number integer NOT NULL,
  user_id uuid NOT NULL,
  user_name character varying,
  status character varying NOT NULL DEFAULT 'reserved'::character varying CHECK (status::text = ANY (ARRAY['reserved'::character varying, 'used'::character varying, 'released'::character varying, 'expired'::character varying]::text[])),
  reserved_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '00:30:00'::interval),
  used_at timestamp with time zone,
  released_at timestamp with time zone,
  CONSTRAINT gr_reservations_pkey PRIMARY KEY (id),
  CONSTRAINT gr_reservations_bill_book_fkey FOREIGN KEY (bill_book_id) REFERENCES public.bill_books(id),
  CONSTRAINT gr_reservations_branch_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT gr_reservations_user_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.grno_allocations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bill_book_id uuid NOT NULL,
  allocated_number integer NOT NULL,
  formatted_gr_no character varying NOT NULL,
  allocated_by uuid NOT NULL,
  allocated_at timestamp with time zone DEFAULT now(),
  status character varying NOT NULL DEFAULT 'RESERVED'::character varying CHECK (status::text = ANY (ARRAY['RESERVED'::character varying, 'USED'::character varying, 'EXPIRED'::character varying, 'CANCELLED'::character varying]::text[])),
  used_at timestamp with time zone,
  used_bilty_id uuid,
  expires_at timestamp with time zone NOT NULL,
  session_id character varying,
  note text,
  CONSTRAINT grno_allocations_pkey PRIMARY KEY (id),
  CONSTRAINT grno_allocations_bill_book_id_fkey FOREIGN KEY (bill_book_id) REFERENCES public.bill_books(id),
  CONSTRAINT grno_allocations_used_bilty_id_fkey FOREIGN KEY (used_bilty_id) REFERENCES public.bilty(id)
);
CREATE TABLE public.income_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  branch_id uuid NOT NULL,
  transaction_date date NOT NULL DEFAULT CURRENT_DATE,
  party_name character varying NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  payment_mode character varying NOT NULL CHECK (payment_mode::text = ANY (ARRAY['cash'::character varying, 'online'::character varying]::text[])),
  receiver character varying NOT NULL,
  description text,
  created_by_staff_id uuid NOT NULL,
  updated_by_staff_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT income_transactions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.kaat_bill_master (
  id bigint NOT NULL DEFAULT nextval('kaat_bill_master_id_seq'::regclass),
  challan_no character varying NOT NULL,
  transport_name character varying,
  transport_gst character varying,
  gr_numbers jsonb NOT NULL DEFAULT '[]'::jsonb,
  total_bilty_count integer DEFAULT 0,
  total_kaat_amount numeric DEFAULT 0,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  printed_yet boolean DEFAULT false,
  transport_admin_id uuid,
  CONSTRAINT kaat_bill_master_pkey PRIMARY KEY (id),
  CONSTRAINT fk_kaat_bill_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT fk_kaat_bill_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.mob_user_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  mob_number character varying,
  session_token text NOT NULL UNIQUE,
  is_active boolean DEFAULT true,
  device_info text,
  expires_at timestamp with time zone NOT NULL,
  logged_out_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT mob_user_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT mob_user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.monthly_bill (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  bill_type character varying NOT NULL CHECK (bill_type::text = ANY (ARRAY['consignor'::character varying, 'consignee'::character varying, 'transport'::character varying, 'custom'::character varying]::text[])),
  bill_name character varying,
  date_from date NOT NULL,
  date_to date NOT NULL,
  consignor_name character varying,
  consignee_name character varying,
  city_name character varying,
  payment_mode character varying,
  total_bilties integer NOT NULL DEFAULT 0,
  total_amount numeric NOT NULL DEFAULT 0,
  paid_amount numeric NOT NULL DEFAULT 0,
  topay_amount numeric NOT NULL DEFAULT 0,
  pdf_template character varying NOT NULL DEFAULT 'portrait'::character varying CHECK (pdf_template::text = ANY (ARRAY['portrait'::character varying, 'landscape'::character varying]::text[])),
  pdf_url text,
  pdf_filename character varying,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT monthly_bill_pkey PRIMARY KEY (id)
);
CREATE TABLE public.monthly_bill_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  monthly_bill_id uuid NOT NULL,
  bilty_type character varying NOT NULL,
  gr_no character varying NOT NULL,
  freight_amount numeric DEFAULT 0,
  rate numeric DEFAULT 0,
  labour_rate numeric DEFAULT 0,
  labour_charge numeric DEFAULT 0,
  bill_charge numeric DEFAULT 0,
  toll_charge numeric DEFAULT 0,
  dd_charge numeric DEFAULT 0,
  other_charge numeric DEFAULT 0,
  total_amount numeric DEFAULT 0,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  pvt_marks text,
  weight numeric DEFAULT 0,
  destination character varying,
  city_id uuid,
  no_of_packages integer DEFAULT 0,
  bilty_date date,
  payment_mode character varying,
  delivery_type character varying,
  CONSTRAINT monthly_bill_items_pkey PRIMARY KEY (id)
);
CREATE TABLE public.monthly_bill_master (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_profile_id uuid NOT NULL,
  billing_start_date date NOT NULL,
  billing_end_date date NOT NULL,
  bill_no character varying NOT NULL,
  bill_date date NOT NULL DEFAULT CURRENT_DATE,
  total_freight numeric DEFAULT 0,
  total_labour numeric DEFAULT 0,
  total_bill_charge numeric DEFAULT 0,
  total_toll numeric DEFAULT 0,
  total_dd numeric DEFAULT 0,
  total_other numeric DEFAULT 0,
  total_amount numeric DEFAULT 0,
  status character varying DEFAULT 'PENDING'::character varying,
  remark text,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT monthly_bill_master_pkey PRIMARY KEY (id)
);
CREATE TABLE public.otp_records (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  otp_code character varying NOT NULL,
  phone_number character varying NOT NULL,
  purpose character varying NOT NULL DEFAULT 'password_reset'::character varying,
  is_verified boolean NOT NULL DEFAULT false,
  is_expired boolean NOT NULL DEFAULT false,
  expires_at timestamp with time zone NOT NULL,
  verified_at timestamp with time zone,
  attempt_count integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public.permanent_details (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  branch_id uuid,
  transport_name character varying,
  gst character varying,
  mobile_number character varying,
  bank_act_no_1 character varying,
  ifsc_code_1 character varying,
  bank_act_no_2 character varying,
  ifsc_code_2 character varying,
  transport_address text,
  website character varying,
  CONSTRAINT permanent_details_pkey PRIMARY KEY (id),
  CONSTRAINT permanent_details_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id)
);
CREATE TABLE public.pod_details (
  id bigint NOT NULL DEFAULT nextval('pod_details_id_seq'::regclass),
  pod_no text NOT NULL,
  gr_no text NOT NULL,
  challan_no text,
  payment_mode text CHECK (payment_mode = ANY (ARRAY['PAID'::text, 'TO-PAY'::text, 'PAID/DD'::text, 'TO-PAY/DD'::text])),
  delivered_at timestamp with time zone,
  mobile_number_1 text,
  mobile_number_2 text,
  total_amount numeric DEFAULT 0,
  amount_given numeric DEFAULT 0,
  reminder text,
  consignor_name text,
  consignor_gst text,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  rs_chrg numeric DEFAULT 50,
  labour_chrg numeric DEFAULT 0,
  CONSTRAINT pod_details_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pohonch (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  pohonch_number character varying NOT NULL UNIQUE,
  transport_name character varying NOT NULL,
  transport_gstin character varying,
  admin_transport_id uuid,
  challan_metadata jsonb NOT NULL DEFAULT '[]'::jsonb,
  bilty_metadata jsonb NOT NULL DEFAULT '[]'::jsonb,
  total_bilties integer NOT NULL DEFAULT 0,
  total_amount numeric NOT NULL DEFAULT 0,
  total_kaat numeric NOT NULL DEFAULT 0,
  total_pf numeric NOT NULL DEFAULT 0,
  total_dd numeric NOT NULL DEFAULT 0,
  total_packages numeric NOT NULL DEFAULT 0,
  total_weight numeric NOT NULL DEFAULT 0,
  is_signed boolean NOT NULL DEFAULT false,
  signed_at timestamp with time zone,
  signed_by uuid,
  created_by uuid NOT NULL,
  updated_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT pohonch_pkey PRIMARY KEY (id),
  CONSTRAINT pohonch_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT pohonch_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id),
  CONSTRAINT pohonch_signed_by_fkey FOREIGN KEY (signed_by) REFERENCES public.users(id)
);
CREATE TABLE public.rates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  branch_id uuid,
  city_id uuid,
  consignor_id uuid,
  rate numeric NOT NULL,
  is_default boolean DEFAULT false,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rates_pkey PRIMARY KEY (id),
  CONSTRAINT rates_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.branches(id),
  CONSTRAINT rates_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id)
);
CREATE TABLE public.salary_advances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  advance_date date NOT NULL DEFAULT CURRENT_DATE,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  reason text,
  salary_payment_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT salary_advances_pkey PRIMARY KEY (id),
  CONSTRAINT salary_advances_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT salary_advances_salary_payment_id_fkey FOREIGN KEY (salary_payment_id) REFERENCES public.salary_payments(id)
);
CREATE TABLE public.salary_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  salary_month date NOT NULL,
  gross_salary numeric NOT NULL CHECK (gross_salary >= 0::numeric),
  total_advance_deducted numeric NOT NULL DEFAULT 0 CHECK (total_advance_deducted >= 0::numeric),
  net_salary_paid numeric NOT NULL CHECK (net_salary_paid >= 0::numeric),
  payment_date date NOT NULL DEFAULT CURRENT_DATE,
  payment_mode text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT salary_payments_pkey PRIMARY KEY (id),
  CONSTRAINT salary_payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.search_tracking_log (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  gr_no character varying NOT NULL,
  searched_by uuid,
  searched_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  source_type character varying DEFAULT 'REG'::character varying,
  CONSTRAINT search_tracking_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.search_tracking_master (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  gr_no character varying NOT NULL UNIQUE,
  source_type character varying NOT NULL DEFAULT 'REG'::character varying,
  first_searched_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  first_searched_by uuid,
  last_searched_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_searched_by uuid,
  search_count integer NOT NULL DEFAULT 1,
  is_complaint boolean NOT NULL DEFAULT false,
  complaint_registered_at timestamp with time zone,
  complaint_registered_by uuid,
  complaint_remark text,
  in_investigation boolean NOT NULL DEFAULT false,
  investigation_started_at timestamp with time zone,
  is_resolved boolean NOT NULL DEFAULT false,
  resolved_at timestamp with time zone,
  resolved_by uuid,
  resolution_remark text,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT search_tracking_master_pkey PRIMARY KEY (id)
);
CREATE TABLE public.staff (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  post character varying NOT NULL,
  mobile_number character varying,
  license_number character varying,
  aadhar_number character varying,
  image_url text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT staff_pkey PRIMARY KEY (id)
);
CREATE TABLE public.station_bilty_deleted (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  original_id uuid NOT NULL,
  station character varying NOT NULL,
  gr_no character varying NOT NULL,
  consignor character varying,
  consignee character varying,
  contents text,
  no_of_packets integer DEFAULT 0,
  weight numeric DEFAULT 0,
  payment_status character varying DEFAULT 'to-pay'::character varying CHECK (payment_status::text = ANY (ARRAY['paid'::character varying::text, 'to-pay'::character varying::text, 'foc'::character varying::text])),
  amount numeric DEFAULT 0,
  pvt_marks text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  delivery_type character varying CHECK (delivery_type::text = ANY (ARRAY['godown'::character varying::text, 'door'::character varying::text])),
  staff_id uuid,
  branch_id uuid,
  e_way_bill character varying,
  deleted_by uuid,
  deleted_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  delete_reason text,
  CONSTRAINT station_bilty_deleted_pkey PRIMARY KEY (id)
);
CREATE TABLE public.station_bilty_summary (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  station character varying NOT NULL,
  gr_no character varying NOT NULL,
  consignor character varying,
  consignee character varying,
  contents text,
  no_of_packets integer DEFAULT 0,
  weight numeric DEFAULT 0,
  payment_status character varying DEFAULT 'to-pay'::character varying CHECK (payment_status::text = ANY (ARRAY['paid'::character varying, 'to-pay'::character varying, 'foc'::character varying]::text[])),
  amount numeric DEFAULT 0,
  pvt_marks text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  delivery_type character varying DEFAULT NULL::character varying CHECK (delivery_type::text = ANY (ARRAY['godown'::character varying, 'door'::character varying]::text[])),
  staff_id uuid,
  branch_id uuid,
  e_way_bill character varying DEFAULT NULL::character varying,
  updated_by uuid,
  w_name character varying,
  is_in_head_branch boolean,
  bilty_image text,
  transit_bilty_image text,
  transport_id uuid,
  transport_name character varying,
  transport_gst character varying,
  city_id uuid,
  CONSTRAINT station_bilty_summary_pkey PRIMARY KEY (id)
);
CREATE TABLE public.transit_details (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  challan_no character varying NOT NULL,
  gr_no character varying NOT NULL UNIQUE,
  bilty_id uuid,
  challan_book_id uuid NOT NULL,
  from_branch_id uuid NOT NULL,
  to_branch_id uuid NOT NULL,
  is_out_of_delivery_from_branch1 boolean DEFAULT false,
  out_of_delivery_from_branch1_date timestamp with time zone,
  is_delivered_at_branch2 boolean DEFAULT false,
  delivered_at_branch2_date timestamp with time zone,
  is_out_of_delivery_from_branch2 boolean DEFAULT false,
  out_of_delivery_from_branch2_date timestamp with time zone,
  is_delivered_at_destination boolean DEFAULT false,
  delivered_at_destination_date timestamp with time zone,
  out_for_door_delivery boolean DEFAULT false,
  out_for_door_delivery_date timestamp with time zone,
  delivery_agent_name character varying DEFAULT NULL::character varying,
  delivery_agent_phone character varying DEFAULT NULL::character varying,
  vehicle_number character varying DEFAULT NULL::character varying,
  remarks text,
  created_by uuid NOT NULL,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT transit_details_pkey PRIMARY KEY (id),
  CONSTRAINT transit_details_bilty_id_fkey FOREIGN KEY (bilty_id) REFERENCES public.bilty(id),
  CONSTRAINT transit_details_challan_book_id_fkey FOREIGN KEY (challan_book_id) REFERENCES public.challan_books(id),
  CONSTRAINT transit_details_from_branch_id_fkey FOREIGN KEY (from_branch_id) REFERENCES public.branches(id),
  CONSTRAINT transit_details_to_branch_id_fkey FOREIGN KEY (to_branch_id) REFERENCES public.branches(id),
  CONSTRAINT transit_details_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT transit_details_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.transport_admin (
  transport_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  transport_name character varying NOT NULL,
  gstin character varying,
  hub_mobile_number character varying,
  owner_name character varying,
  website character varying,
  address text,
  sample_ref_image text,
  sample_challan_image text,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT transport_admin_pkey PRIMARY KEY (transport_id)
);
CREATE TABLE public.transport_hub_rates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  transport_id uuid,
  transport_name character varying,
  destination_city_id uuid NOT NULL,
  goods_type character varying,
  pricing_mode character varying NOT NULL DEFAULT 'per_kg'::character varying,
  rate_per_kg numeric,
  rate_per_pkg numeric,
  min_charge numeric DEFAULT 0,
  metadata jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  bilty_chrg numeric,
  ewb_chrg numeric,
  other_chrg numeric,
  labour_chrg numeric,
  CONSTRAINT transport_hub_rates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.transport_otp_records (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  transport_id uuid,
  mob_number character varying,
  otp_code character varying,
  purpose character varying DEFAULT 'login'::character varying,
  is_verified boolean DEFAULT false,
  is_expired boolean DEFAULT false,
  attempt_count integer DEFAULT 0,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transport_otp_records_pkey PRIMARY KEY (id)
);
CREATE TABLE public.transport_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  transport_id uuid,
  mob_number character varying,
  session_token text,
  device_info text,
  ip_address character varying,
  is_active boolean DEFAULT true,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  logged_out_at timestamp with time zone,
  CONSTRAINT transport_sessions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.transporter_updates (
  id bigint NOT NULL DEFAULT nextval('transporter_updates_id_seq'::regclass),
  updated_by uuid NOT NULL,
  challan_no character varying,
  gr_no character varying,
  ewb_number character varying NOT NULL,
  transporter_id character varying NOT NULL,
  transporter_name character varying NOT NULL,
  user_gstin character varying,
  is_success boolean NOT NULL DEFAULT false,
  update_status character varying,
  error_message text,
  pdf_url text,
  update_date character varying,
  raw_result_metadata jsonb,
  updated_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  is_downloaded boolean NOT NULL DEFAULT false,
  CONSTRAINT transporter_updates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.transports (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  transport_name character varying NOT NULL,
  city_id uuid,
  city_name character varying NOT NULL,
  address text NOT NULL,
  gst_number character varying,
  mob_number character varying,
  branch_owner_name character varying,
  website character varying,
  transport_admin_id uuid,
  created_by character varying,
  updated_by character varying,
  is_prior boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transports_pkey PRIMARY KEY (id),
  CONSTRAINT transports_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id),
  CONSTRAINT transports_transport_admin_id_fkey FOREIGN KEY (transport_admin_id) REFERENCES public.transport_admin(transport_id)
);
CREATE TABLE public.trucks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  truck_number character varying NOT NULL UNIQUE,
  truck_type character varying,
  tyre_count integer,
  brand character varying,
  year_of_manufacturing integer,
  rc_number character varying,
  insurance_number character varying,
  permit_number character varying,
  owner_id uuid,
  fuel_type character varying,
  loading_capacity numeric,
  is_active boolean DEFAULT true,
  is_available boolean DEFAULT true,
  current_location character varying,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT trucks_pkey PRIMARY KEY (id),
  CONSTRAINT trucks_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.staff(id)
);
CREATE TABLE public.user_details (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  email character varying,
  phone character varying,
  date_of_birth date,
  gender character varying,
  employee_code character varying,
  department character varying,
  date_of_joining date,
  employment_type character varying,
  address_line1 text,
  address_line2 text,
  city character varying,
  state character varying,
  pincode character varying,
  aadhar_number character varying,
  pan_number character varying,
  salary_month integer NOT NULL,
  bank_name character varying,
  account_number character varying,
  ifsc_code character varying,
  qualification character varying,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE public.user_modules (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  module_name character varying NOT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_modules_pkey PRIMARY KEY (id),
  CONSTRAINT user_modules_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  login_time timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  logout_time timestamp with time zone,
  ip_address inet,
  user_agent text,
  is_active boolean DEFAULT true,
  CONSTRAINT user_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_tokens (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  token text NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  is_revoked boolean DEFAULT false,
  CONSTRAINT user_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT user_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  username character varying NOT NULL UNIQUE,
  password_hash text NOT NULL,
  name character varying,
  post character varying,
  branch_id uuid,
  image_url text,
  is_active boolean DEFAULT true,
  is_staff boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.users_otp_records (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  mob_number character varying NOT NULL,
  otp_code character varying NOT NULL,
  purpose character varying DEFAULT 'login'::character varying,
  is_verified boolean DEFAULT false,
  is_expired boolean DEFAULT false,
  attempt_count integer DEFAULT 0,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT users_otp_records_pkey PRIMARY KEY (id),
  CONSTRAINT users_otp_records_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);